version: '3.4'

services:
  productdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
     - ACCEPT_EULA=Y
    
    ports:
      - "8002:1433"                        





  rbac.api:
    image: ${DOCKER_REGISTRY-}rbacapi
    build:
      context: .
      dockerfile: RBAC_Project/Dockerfile
    depends_on:
     - productdb
    ports:
    - "8001:80"
    environment:
    - DB-HOST=productdb
    - DB-NAME=Rbac_DataBase
    
